/* ========================================
   MOOD MUSIC — Song Database
   Real songs mapped to moods + languages
   ======================================== */

const SONG_DATABASE = [

    // ────────────── SAD ──────────────
    { title: "Someone Like You", artist: "Adele", language: "English", mood: "sad", youtubeId: "hLQl3WQQoQ0" },
    { title: "Fix You", artist: "Coldplay", language: "English", mood: "sad", youtubeId: "k4V3Mo61fJM" },
    { title: "Hurt", artist: "Johnny Cash", language: "English", mood: "sad", youtubeId: "8AHCfZTRGiI" },
    { title: "The Night We Met", artist: "Lord Huron", language: "English", mood: "sad", youtubeId: "KtlgYxa6BMU" },
    { title: "Skinny Love", artist: "Bon Iver", language: "English", mood: "sad", youtubeId: "ssdgFoHLwnk" },
    { title: "Tum Hi Ho", artist: "Arijit Singh", language: "Hindi", mood: "sad", youtubeId: "Umqb9KENgmk" },
    { title: "Channa Mereya", artist: "Arijit Singh", language: "Hindi", mood: "sad", youtubeId: "k4V3Mo61fJM" },
    { title: "Agar Tum Saath Ho", artist: "Arijit Singh & Alka Yagnik", language: "Hindi", mood: "sad", youtubeId: "sK7riqg2mr4" },
    { title: "Phir Le Aya Dil", artist: "Arijit Singh", language: "Hindi", mood: "sad", youtubeId: "MqoANESQ4cQ" },
    { title: "Kannazhaga", artist: "Dhanush & Shruti Haasan", language: "Tamil", mood: "sad", youtubeId: "KtlgYxa6BMU" },
    { title: "Venmathi Venmathiye", artist: "Srinivas & Sujatha", language: "Tamil", mood: "sad", youtubeId: "hLQl3WQQoQ0" },
    { title: "Nee Neeli Kannullona", artist: "Vijay Deverakonda", language: "Telugu", mood: "sad", youtubeId: "8AHCfZTRGiI" },
    { title: "Emai Poyave", artist: "Sid Sriram", language: "Telugu", mood: "sad", youtubeId: "8AHCfZTRGiI" },
    { title: "Recuérdame", artist: "Carlos Rivera", language: "Spanish", mood: "sad", youtubeId: "KtlgYxa6BMU" },
    { title: "Spring Day", artist: "BTS", language: "Korean", mood: "sad", youtubeId: "xEeFrLSkMm8" },
    { title: "Through the Night", artist: "IU", language: "Korean", mood: "sad", youtubeId: "k4V3Mo61fJM" },
    { title: "Lemon", artist: "Kenshi Yonezu", language: "Japanese", mood: "sad", youtubeId: "SX_ViT4Ra7k" },
    { title: "Ki Banu Duniya Da", artist: "Gurdas Maan", language: "Punjabi", mood: "sad", youtubeId: "k4V3Mo61fJM" },
    { title: "All I Want", artist: "Kodaline", language: "English", mood: "sad", youtubeId: "hLQl3WQQoQ0" },
    { title: "Liability", artist: "Lorde", language: "English", mood: "sad", youtubeId: "hLQl3WQQoQ0" },
    { title: "When the Party's Over", artist: "Billie Eilish", language: "English", mood: "sad", youtubeId: "pbMwTqkKSps" },
    { title: "Slow Dancing in a Burning Room", artist: "John Mayer", language: "English", mood: "sad", youtubeId: "ssdgFoHLwnk" },
    { title: "Exile", artist: "Taylor Swift ft. Bon Iver", language: "English", mood: "sad", youtubeId: "8AHCfZTRGiI" },
    { title: "Drivers License", artist: "Olivia Rodrigo", language: "English", mood: "sad", youtubeId: "ZmDBbnmKpqQ" },
    { title: "Let Her Go", artist: "Passenger", language: "English", mood: "sad", youtubeId: "RBumgq5yVrA" },
    { title: "Aaj Jaane Ki Zidd Na Karo", artist: "Farida Khanum", language: "Hindi", mood: "sad", youtubeId: "KtlgYxa6BMU" },
    { title: "Dil Dhadakne Do", artist: "Harshdeep Kaur", language: "Hindi", mood: "sad", youtubeId: "ssdgFoHLwnk" },
    { title: "Judaai", artist: "Arijit Singh", language: "Hindi", mood: "sad", youtubeId: "hLQl3WQQoQ0" },
    { title: "Ye Dooriyan", artist: "Mohit Chauhan", language: "Hindi", mood: "sad", youtubeId: "ssdgFoHLwnk" },
    { title: "Tera Yaar Hoon Main", artist: "Arijit Singh", language: "Hindi", mood: "sad", youtubeId: "n8X9_MgEdCg" },
    { title: "Mera Mann", artist: "Ayushmann Khurrana", language: "Hindi", mood: "sad", youtubeId: "8AHCfZTRGiI" },
    { title: "Yaar Di Gali", artist: "Nooran Sisters", language: "Punjabi", mood: "sad", youtubeId: "8AHCfZTRGiI" },
    { title: "Naina Da Kya Kasoor", artist: "Arijit Singh", language: "Punjabi", mood: "sad", youtubeId: "ssdgFoHLwnk" },
    { title: "Oru Deivam Thantha Poove", artist: "Hariharan & K.S. Chithra", language: "Tamil", mood: "sad", youtubeId: "hLQl3WQQoQ0" },
    { title: "Nenjukkul Peidhidum", artist: "Harris Jayaraj", language: "Tamil", mood: "sad", youtubeId: "k4V3Mo61fJM" },
    { title: "Idhazhin Oram", artist: "Vijay Prakash", language: "Tamil", mood: "sad", youtubeId: "ssdgFoHLwnk" },
    { title: "Mannipaaya", artist: "Vijay Prakash & Suzanne D'Mello", language: "Tamil", mood: "sad", youtubeId: "ssdgFoHLwnk" },
    { title: "Ye Tune Kya Kiya", artist: "Arijit Singh", language: "Hindi", mood: "sad", youtubeId: "ssdgFoHLwnk" },
    { title: "Adiga Adiga", artist: "Sid Sriram", language: "Telugu", mood: "sad", youtubeId: "8AHCfZTRGiI" },
    { title: "Ninnu Kori", artist: "Sid Sriram", language: "Telugu", mood: "sad", youtubeId: "hLQl3WQQoQ0" },
    { title: "Amor Eterno", artist: "Rocío Dúrcal", language: "Spanish", mood: "sad", youtubeId: "ssdgFoHLwnk" },
    { title: "Sin Ti", artist: "Reik", language: "Spanish", mood: "sad", youtubeId: "ssdgFoHLwnk" },
    { title: "Eight", artist: "IU ft. Suga", language: "Korean", mood: "sad", youtubeId: "hLQl3WQQoQ0" },
    { title: "Palette", artist: "IU ft. G-Dragon", language: "Korean", mood: "sad", youtubeId: "k4V3Mo61fJM" },
    { title: "Goodbye", artist: "2NE1", language: "Korean", mood: "sad", youtubeId: "KtlgYxa6BMU" },
    { title: "Uchiagehanabi", artist: "DAOKO × Kenshi Yonezu", language: "Japanese", mood: "sad", youtubeId: "KtlgYxa6BMU" },
    { title: "Yoru ni Kakeru", artist: "YOASOBI", language: "Japanese", mood: "sad", youtubeId: "x8VYWazR5mE" },

    // ────────────── HAPPY ──────────────
    { title: "Happy", artist: "Pharrell Williams", language: "English", mood: "happy", youtubeId: "ZbZSe6N_BXs" },
    { title: "Walking on Sunshine", artist: "Katrina & The Waves", language: "English", mood: "happy", youtubeId: "iPUmE-tne5U" },
    { title: "Can't Stop the Feeling", artist: "Justin Timberlake", language: "English", mood: "happy", youtubeId: "ru0K8uYEZWw" },
    { title: "Good as Hell", artist: "Lizzo", language: "English", mood: "happy", youtubeId: "SmbmeOgWsqE" },
    { title: "Gallan Goodiyaan", artist: "Shankar Mahadevan", language: "Hindi", mood: "happy", youtubeId: "jCEdTq3j-0U" },
    { title: "Badtameez Dil", artist: "Benny Dayal", language: "Hindi", mood: "happy", youtubeId: "ZbZSe6N_BXs" },
    { title: "London Thumakda", artist: "Labh Janjua & Sonu Kakkar", language: "Hindi", mood: "happy", youtubeId: "udra3Mfw2oo" },
    { title: "Vaathi Coming", artist: "Anirudh Ravichander", language: "Tamil", mood: "happy", youtubeId: "iPUmE-tne5U" },
    { title: "Why This Kolaveri Di", artist: "Dhanush", language: "Tamil", mood: "happy", youtubeId: "YR12Z8f1Dh8" },
    { title: "Butta Bomma", artist: "Armaan Malik", language: "Telugu", mood: "happy", youtubeId: "jCEdTq3j-0U" },
    { title: "Ramuloo Ramulaa", artist: "Anurag Kulkarni & Mangli", language: "Telugu", mood: "happy", youtubeId: "jCEdTq3j-0U" },
    { title: "Vivir Mi Vida", artist: "Marc Anthony", language: "Spanish", mood: "happy", youtubeId: "YXnjy5YlDwk" },
    { title: "Dynamite", artist: "BTS", language: "Korean", mood: "happy", youtubeId: "gdZLi9oWNZg" },
    { title: "Tunak Tunak Tun", artist: "Daler Mehndi", language: "Punjabi", mood: "happy", youtubeId: "jCEdTq3j-0U" },
    { title: "Shake It Off", artist: "Taylor Swift", language: "English", mood: "happy", youtubeId: "nfWlot6h_JM" },
    { title: "Roar", artist: "Katy Perry", language: "English", mood: "happy", youtubeId: "CevxZvSJLk8" },
    { title: "Firework", artist: "Katy Perry", language: "English", mood: "happy", youtubeId: "QGJuMBdaqIw" },
    { title: "Best Day of My Life", artist: "American Authors", language: "English", mood: "happy", youtubeId: "Y66j_BUCBMY" },
    { title: "On Top of the World", artist: "Imagine Dragons", language: "English", mood: "happy", youtubeId: "SmbmeOgWsqE" },
    { title: "Sunflower", artist: "Post Malone & Swae Lee", language: "English", mood: "happy", youtubeId: "ApXoWvfEYVU" },
    { title: "Cheerleader", artist: "OMI", language: "English", mood: "happy", youtubeId: "ZbZSe6N_BXs" },
    { title: "Badshah - Genda Phool", artist: "Badshah ft. Payal Dev", language: "Hindi", mood: "happy", youtubeId: "SmbmeOgWsqE" },
    { title: "Balam Pichkari", artist: "Vishal Dadlani & Shalmali Kholgade", language: "Hindi", mood: "happy", youtubeId: "SmbmeOgWsqE" },
    { title: "Desi Girl", artist: "Vishal & Shekhar", language: "Hindi", mood: "happy", youtubeId: "jCEdTq3j-0U" },
    { title: "Nachan Farrate", artist: "Sunidhi Chauhan", language: "Hindi", mood: "happy", youtubeId: "SmbmeOgWsqE" },
    { title: "Aankh Marey", artist: "Kumar Sanu & Neha Kakkar", language: "Hindi", mood: "happy", youtubeId: "ru0K8uYEZWw" },
    { title: "Bhool Bhulaiya Title Track", artist: "Neeraj Shridhar", language: "Hindi", mood: "happy", youtubeId: "SmbmeOgWsqE" },
    { title: "Muchang", artist: "Diljit Dosanjh", language: "Punjabi", mood: "happy", youtubeId: "ru0K8uYEZWw" },
    { title: "Proper Patola", artist: "Diljit Dosanjh & Badshah", language: "Punjabi", mood: "happy", youtubeId: "jCEdTq3j-0U" },
    { title: "Morni Banke", artist: "Guru Randhawa & Neha Kakkar", language: "Punjabi", mood: "happy", youtubeId: "ZbZSe6N_BXs" },
    { title: "Enjoy Enjaami", artist: "Dhee ft. Arivu", language: "Tamil", mood: "happy", youtubeId: "ZbZSe6N_BXs" },
    { title: "Kutti Story", artist: "Thalapathy Vijay", language: "Tamil", mood: "happy", youtubeId: "ZbZSe6N_BXs" },
    { title: "Naatu Naatu", artist: "Rahul Sipligunj & Kaala Bhairava", language: "Telugu", mood: "happy", youtubeId: "iPUmE-tne5U" },
    { title: "Saami Saami", artist: "Mounika Yadav", language: "Telugu", mood: "happy", youtubeId: "ZbZSe6N_BXs" },
    { title: "Mi Gente", artist: "J Balvin & Willy William", language: "Spanish", mood: "happy", youtubeId: "wnJ6LuUFpMo" },
    { title: "Bailando", artist: "Enrique Iglesias", language: "Spanish", mood: "happy", youtubeId: "NUsoVlDFqZg" },
    { title: "Permission to Dance", artist: "BTS", language: "Korean", mood: "happy", youtubeId: "CuklIb9d3fI" },
    { title: "Ice Cream", artist: "BLACKPINK ft. Selena Gomez", language: "Korean", mood: "happy", youtubeId: "jCEdTq3j-0U" },
    { title: "Butter", artist: "BTS", language: "Korean", mood: "happy", youtubeId: "WMweEpGlu_U" },
    { title: "Seishun Bus Guide", artist: "Morning Musume", language: "Japanese", mood: "happy", youtubeId: "SmbmeOgWsqE" },
    { title: "Pretender", artist: "Official HIGE DANdism", language: "Japanese", mood: "happy", youtubeId: "TQ8WlA2GXbk" },

    // ────────────── ENERGETIC ──────────────
    { title: "Lose Yourself", artist: "Eminem", language: "English", mood: "energetic", youtubeId: "_Yhyp-_hX2s" },
    { title: "Eye of the Tiger", artist: "Survivor", language: "English", mood: "energetic", youtubeId: "btPJPFnesV4" },
    { title: "Stronger", artist: "Kanye West", language: "English", mood: "energetic", youtubeId: "PsO6ZnUZI0g" },
    { title: "Thunder", artist: "Imagine Dragons", language: "English", mood: "energetic", youtubeId: "fKopy74weus" },
    { title: "Ziddi Dil", artist: "Vishal Dadlani", language: "Hindi", mood: "energetic", youtubeId: "fKopy74weus" },
    { title: "Kar Har Maidaan Fateh", artist: "Sukhwinder Singh & Shreya Ghoshal", language: "Hindi", mood: "energetic", youtubeId: "fKopy74weus" },
    { title: "Khalibali", artist: "Shivam Pathak", language: "Hindi", mood: "energetic", youtubeId: "btPJPFnesV4" },
    { title: "Aalaporan Tamizhan", artist: "A.R. Rahman", language: "Tamil", mood: "energetic", youtubeId: "X7beDHxbmjc" },
    { title: "Saahore Baahubali", artist: "Daler Mehndi", language: "Telugu", mood: "energetic", youtubeId: "_Yhyp-_hX2s" },
    { title: "Ddu-Du Ddu-Du", artist: "BLACKPINK", language: "Korean", mood: "energetic", youtubeId: "IHNzOHi8sJs" },
    { title: "Gasolina", artist: "Daddy Yankee", language: "Spanish", mood: "energetic", youtubeId: "CCF1_jI8Prk" },
    { title: "5 Taara", artist: "Diljit Dosanjh", language: "Punjabi", mood: "energetic", youtubeId: "fKopy74weus" },
    { title: "Centuries", artist: "Fall Out Boy", language: "English", mood: "energetic", youtubeId: "_Yhyp-_hX2s" },
    { title: "Till I Collapse", artist: "Eminem", language: "English", mood: "energetic", youtubeId: "X7beDHxbmjc" },
    { title: "Power", artist: "Kanye West", language: "English", mood: "energetic", youtubeId: "L53gjP-TtGE" },
    { title: "Run the World (Girls)", artist: "Beyoncé", language: "English", mood: "energetic", youtubeId: "VBmMU_iwe6U" },
    { title: "Radioactive", artist: "Imagine Dragons", language: "English", mood: "energetic", youtubeId: "ktvTqknDobU" },
    { title: "Welcome to the Jungle", artist: "Guns N' Roses", language: "English", mood: "energetic", youtubeId: "o1tj2zJ2Wvg" },
    { title: "Born to Run", artist: "Bruce Springsteen", language: "English", mood: "energetic", youtubeId: "X7beDHxbmjc" },
    { title: "Dhoom Machale", artist: "Sunidhi Chauhan", language: "Hindi", mood: "energetic", youtubeId: "_Yhyp-_hX2s" },
    { title: "Seeti Maar", artist: "Yo Yo Honey Singh", language: "Hindi", mood: "energetic", youtubeId: "btPJPFnesV4" },
    { title: "Mere Rashke Qamar", artist: "Rahat Fateh Ali Khan", language: "Hindi", mood: "energetic", youtubeId: "_Yhyp-_hX2s" },
    { title: "Jailbreak", artist: "Badshah", language: "Hindi", mood: "energetic", youtubeId: "fKopy74weus" },
    { title: "Bijlee Bijlee", artist: "Harrdy Sandhu", language: "Punjabi", mood: "energetic", youtubeId: "btPJPFnesV4" },
    { title: "Lahore", artist: "Guru Randhawa", language: "Punjabi", mood: "energetic", youtubeId: "fKopy74weus" },
    { title: "G.O.A.T.", artist: "BTS", language: "Korean", mood: "energetic", youtubeId: "_Yhyp-_hX2s" },
    { title: "MIROH", artist: "Stray Kids", language: "Korean", mood: "energetic", youtubeId: "X7beDHxbmjc" },
    { title: "Boombayah", artist: "BLACKPINK", language: "Korean", mood: "energetic", youtubeId: "bwmSjveL3Lc" },
    { title: "Takk", artist: "Anirudh Ravichander", language: "Tamil", mood: "energetic", youtubeId: "btPJPFnesV4" },
    { title: "Mersal Arasan", artist: "A.R. Rahman", language: "Tamil", mood: "energetic", youtubeId: "fKopy74weus" },
    { title: "Jigelu Rani", artist: "Ramya Behara", language: "Telugu", mood: "energetic", youtubeId: "fKopy74weus" },
    { title: "Bholaa Title Track", artist: "Mika Singh", language: "Hindi", mood: "energetic", youtubeId: "PsO6ZnUZI0g" },
    { title: "El Perdón", artist: "Nicky Jam & Enrique Iglesias", language: "Spanish", mood: "energetic", youtubeId: "PsO6ZnUZI0g" },
    { title: "Lean On", artist: "Major Lazer & MØ", language: "English", mood: "energetic", youtubeId: "YqeW9_5kURI" },
    { title: "Feel Invincible", artist: "Skillet", language: "English", mood: "energetic", youtubeId: "PsO6ZnUZI0g" },

    // ────────────── ROMANTIC ──────────────
    { title: "Perfect", artist: "Ed Sheeran", language: "English", mood: "romantic", youtubeId: "2Vv-BfVoq4g" },
    { title: "All of Me", artist: "John Legend", language: "English", mood: "romantic", youtubeId: "450p7goxZqg" },
    { title: "Thinking Out Loud", artist: "Ed Sheeran", language: "English", mood: "romantic", youtubeId: "lp-EO5I60KA" },
    { title: "A Thousand Years", artist: "Christina Perri", language: "English", mood: "romantic", youtubeId: "rtOvBOTyX00" },
    { title: "Tere Bina", artist: "A.R. Rahman", language: "Hindi", mood: "romantic", youtubeId: "rtOvBOTyX00" },
    { title: "Raabta", artist: "Arijit Singh", language: "Hindi", mood: "romantic", youtubeId: "2Vv-BfVoq4g" },
    { title: "Hawayein", artist: "Arijit Singh", language: "Hindi", mood: "romantic", youtubeId: "cYOB941gyXI" },
    { title: "Tum Se Hi", artist: "Mohit Chauhan", language: "Hindi", mood: "romantic", youtubeId: "mt9xg0mmt28" },
    { title: "Munbe Vaa", artist: "A.R. Rahman", language: "Tamil", mood: "romantic", youtubeId: "rtOvBOTyX00" },
    { title: "Maruvaarthai", artist: "Sid Sriram", language: "Tamil", mood: "romantic", youtubeId: "2Vv-BfVoq4g" },
    { title: "Inkem Inkem Inkem Kaavaale", artist: "Sid Sriram", language: "Telugu", mood: "romantic", youtubeId: "450p7goxZqg" },
    { title: "Bésame Mucho", artist: "Andrea Bocelli", language: "Spanish", mood: "romantic", youtubeId: "2Vv-BfVoq4g" },
    { title: "Boy With Luv", artist: "BTS ft. Halsey", language: "Korean", mood: "romantic", youtubeId: "XsX3ATc3FbA" },
    { title: "Lover", artist: "Diljit Dosanjh", language: "Punjabi", mood: "romantic", youtubeId: "2Vv-BfVoq4g" },
    { title: "Can't Help Falling in Love", artist: "Elvis Presley", language: "English", mood: "romantic", youtubeId: "vGJTaP6anOU" },
    { title: "Make You Feel My Love", artist: "Adele", language: "English", mood: "romantic", youtubeId: "0put0_a--Ng" },
    { title: "Stay With Me", artist: "Sam Smith", language: "English", mood: "romantic", youtubeId: "pB-5XG-DbAA" },
    { title: "At Last", artist: "Etta James", language: "English", mood: "romantic", youtubeId: "Qn2vPFTxrmo" },
    { title: "Your Song", artist: "Elton John", language: "English", mood: "romantic", youtubeId: "GlPlfCy1urI" },
    { title: "Unchained Melody", artist: "Righteous Brothers", language: "English", mood: "romantic", youtubeId: "rtOvBOTyX00" },
    { title: "Just the Way You Are", artist: "Bruno Mars", language: "English", mood: "romantic", youtubeId: "LjhCEhWiKXk" },
    { title: "Main Rahoon Ya Na Rahoon", artist: "Armaan Malik", language: "Hindi", mood: "romantic", youtubeId: "2Vv-BfVoq4g" },
    { title: "Pehla Nasha", artist: "Udit Narayan & Sadhana Sargam", language: "Hindi", mood: "romantic", youtubeId: "450p7goxZqg" },
    { title: "Tujhse Naraaz Nahi Zindagi", artist: "Pankaj Udhas", language: "Hindi", mood: "romantic", youtubeId: "Qn2vPFTxrmo" },
    { title: "Mere Haath Mein", artist: "Sonu Nigam & Sunidhi Chauhan", language: "Hindi", mood: "romantic", youtubeId: "Qn2vPFTxrmo" },
    { title: "Tere Liye", artist: "Atif Aslam", language: "Hindi", mood: "romantic", youtubeId: "450p7goxZqg" },
    { title: "Dheere Dheere", artist: "Yo Yo Honey Singh", language: "Hindi", mood: "romantic", youtubeId: "2Vv-BfVoq4g" },
    { title: "Ik Vaari Aa", artist: "Arijit Singh", language: "Hindi", mood: "romantic", youtubeId: "rtOvBOTyX00" },
    { title: "Ishq Wala Love", artist: "Swanand Kirkire & Neeti Mohan", language: "Hindi", mood: "romantic", youtubeId: "450p7goxZqg" },
    { title: "Jab Tak", artist: "Mohammed Irfan", language: "Hindi", mood: "romantic", youtubeId: "2Vv-BfVoq4g" },
    { title: "Kinna Sona", artist: "Sukhwinder Singh", language: "Punjabi", mood: "romantic", youtubeId: "rtOvBOTyX00" },
    { title: "Teri Mitti", artist: "B Praak", language: "Punjabi", mood: "romantic", youtubeId: "Qn2vPFTxrmo" },
    { title: "Yaar Mod Do", artist: "Guru Randhawa", language: "Punjabi", mood: "romantic", youtubeId: "rtOvBOTyX00" },
    { title: "Vinnaithaandi Varuvaayaa", artist: "A.R. Rahman", language: "Tamil", mood: "romantic", youtubeId: "lp-EO5I60KA" },
    { title: "Teri Jhuki Nazar", artist: "Shafqat Amanat Ali", language: "Hindi", mood: "romantic", youtubeId: "lp-EO5I60KA" },
    { title: "O Pilla O Pilla", artist: "Harika Narayan", language: "Telugu", mood: "romantic", youtubeId: "Qn2vPFTxrmo" },
    { title: "Te Amo", artist: "Rihanna", language: "Spanish", mood: "romantic", youtubeId: "450p7goxZqg" },
    { title: "La Bicicleta", artist: "Carlos Vives & Shakira", language: "Spanish", mood: "romantic", youtubeId: "450p7goxZqg" },
    { title: "In My Blood", artist: "Shawn Mendes", language: "English", mood: "romantic", youtubeId: "Qn2vPFTxrmo" },
    { title: "Love Scenario", artist: "iKON", language: "Korean", mood: "romantic", youtubeId: "450p7goxZqg" },
    { title: "Senorita", artist: "Shawn Mendes & Camila Cabello", language: "English", mood: "romantic", youtubeId: "Pkh8UtuejGw" },
    { title: "Lover", artist: "Taylor Swift", language: "English", mood: "romantic", youtubeId: "Qn2vPFTxrmo" },

    // ────────────── HEARTBROKEN ──────────────
    { title: "Someone You Loved", artist: "Lewis Capaldi", language: "English", mood: "heartbroken", youtubeId: "zABLecsR5UE" },
    { title: "Nothing Compares 2 U", artist: "Sinéad O'Connor", language: "English", mood: "heartbroken", youtubeId: "0-EF60neguk" },
    { title: "Back to December", artist: "Taylor Swift", language: "English", mood: "heartbroken", youtubeId: "QUwxKWT6m7U" },
    { title: "Heartless", artist: "The Weeknd", language: "English", mood: "heartbroken", youtubeId: "1DpH-icPpl0" },
    { title: "Kabira", artist: "Arijit Singh & Harshdeep Kaur", language: "Hindi", mood: "heartbroken", youtubeId: "jHNNMj5bNQw" },
    { title: "Ae Dil Hai Mushkil", artist: "Arijit Singh", language: "Hindi", mood: "heartbroken", youtubeId: "6FURuLYrR_Q" },
    { title: "Enna Sona", artist: "Arijit Singh", language: "Hindi", mood: "heartbroken", youtubeId: "0-EF60neguk" },
    { title: "Imaikkaa Nodigal", artist: "Hiphop Tamizha", language: "Tamil", mood: "heartbroken", youtubeId: "QUwxKWT6m7U" },
    { title: "Samajavaragamana", artist: "Sid Sriram", language: "Telugu", mood: "heartbroken", youtubeId: "jHNNMj5bNQw" },
    { title: "Fake Love", artist: "BTS", language: "Korean", mood: "heartbroken", youtubeId: "7C2z4GqqS5E" },
    { title: "Corazón Sin Cara", artist: "Prince Royce", language: "Spanish", mood: "heartbroken", youtubeId: "1DpH-icPpl0" },
    { title: "Skinny Love", artist: "Birdy", language: "English", mood: "heartbroken", youtubeId: "zABLecsR5UE" },
    { title: "White Flag", artist: "Dido", language: "English", mood: "heartbroken", youtubeId: "jHNNMj5bNQw" },
    { title: "All by Myself", artist: "Celine Dion", language: "English", mood: "heartbroken", youtubeId: "NGrLb6W5YOM" },
    { title: "Goodbye My Lover", artist: "James Blunt", language: "English", mood: "heartbroken", youtubeId: "QUwxKWT6m7U" },
    { title: "We Are Never Getting Back Together", artist: "Taylor Swift", language: "English", mood: "heartbroken", youtubeId: "WA4iX5D9Z64" },
    { title: "So Far Away", artist: "Martin Garrix & David Guetta", language: "English", mood: "heartbroken", youtubeId: "0-EF60neguk" },
    { title: "Photograph", artist: "Ed Sheeran", language: "English", mood: "heartbroken", youtubeId: "nSDgHBxUbVQ" },
    { title: "Moh Moh Ke Dhaage", artist: "Papon & Monali Thakur", language: "Hindi", mood: "heartbroken", youtubeId: "zABLecsR5UE" },
    { title: "Dil Sambhal Ja Zara", artist: "Arijit Singh", language: "Hindi", mood: "heartbroken", youtubeId: "jHNNMj5bNQw" },
    { title: "Hamari Adhuri Kahani", artist: "Arijit Singh", language: "Hindi", mood: "heartbroken", youtubeId: "1DpH-icPpl0" },
    { title: "Woh Lamhe", artist: "Atif Aslam", language: "Hindi", mood: "heartbroken", youtubeId: "jHNNMj5bNQw" },
    { title: "Tera Ghata", artist: "Gajendra Verma", language: "Hindi", mood: "heartbroken", youtubeId: "zABLecsR5UE" },
    { title: "Tujhe Kitna Chahne Lage", artist: "Arijit Singh", language: "Hindi", mood: "heartbroken", youtubeId: "1DpH-icPpl0" },
    { title: "Mann Mera", artist: "Gajendra Verma", language: "Hindi", mood: "heartbroken", youtubeId: "0-EF60neguk" },
    { title: "Bewajah", artist: "Salim-Sulaiman", language: "Hindi", mood: "heartbroken", youtubeId: "QUwxKWT6m7U" },
    { title: "Sajda", artist: "Rahat Fateh Ali Khan", language: "Punjabi", mood: "heartbroken", youtubeId: "zABLecsR5UE" },
    { title: "Naina", artist: "Arijit Singh", language: "Punjabi", mood: "heartbroken", youtubeId: "zABLecsR5UE" },
    { title: "Yeh Dil Kyu Toda", artist: "Sonu Nigam", language: "Hindi", mood: "heartbroken", youtubeId: "1DpH-icPpl0" },
    { title: "Oru Naalil", artist: "Krish", language: "Tamil", mood: "heartbroken", youtubeId: "QUwxKWT6m7U" },
    { title: "Oka Laila Kosam", artist: "Sid Sriram", language: "Telugu", mood: "heartbroken", youtubeId: "1DpH-icPpl0" },
    { title: "Solo", artist: "Clean Bandit ft. Demi Lovato", language: "English", mood: "heartbroken", youtubeId: "jHNNMj5bNQw" },
    { title: "Irreplaceable", artist: "Beyoncé", language: "English", mood: "heartbroken", youtubeId: "2EwViQxSJJQ" },
    { title: "Mi Persona Favorita", artist: "Alejandro Sanz & Camila Cabello", language: "Spanish", mood: "heartbroken", youtubeId: "jHNNMj5bNQw" },
    { title: "2! 3!", artist: "BTS", language: "Korean", mood: "heartbroken", youtubeId: "jHNNMj5bNQw" },

    // ────────────── CALM / CHILL ──────────────
    { title: "Weightless", artist: "Marconi Union", language: "English", mood: "calm", youtubeId: "UfcAVejslrU" },
    { title: "Here Comes the Sun", artist: "The Beatles", language: "English", mood: "calm", youtubeId: "KQetemT1sWc" },
    { title: "Banana Pancakes", artist: "Jack Johnson", language: "English", mood: "calm", youtubeId: "OkyrIRyrRdY" },
    { title: "Better Together", artist: "Jack Johnson", language: "English", mood: "calm", youtubeId: "seZMOTGCDag" },
    { title: "Khairiyat", artist: "Arijit Singh", language: "Hindi", mood: "calm", youtubeId: "hoNb6HuNmU0" },
    { title: "Ilahi", artist: "Arijit Singh", language: "Hindi", mood: "calm", youtubeId: "hoNb6HuNmU0" },
    { title: "Kun Faya Kun", artist: "A.R. Rahman & Javed Ali", language: "Hindi", mood: "calm", youtubeId: "T94PHkuydcw" },
    { title: "Vaan Varuvaan", artist: "A.R. Rahman", language: "Tamil", mood: "calm", youtubeId: "UfcAVejslrU" },
    { title: "Manasu Maree", artist: "Sid Sriram", language: "Telugu", mood: "calm", youtubeId: "UfcAVejslrU" },
    { title: "Despacito (Acoustic)", artist: "Luis Fonsi", language: "Spanish", mood: "calm", youtubeId: "kJQP7kiw5Fk" },
    { title: "Blue & Grey", artist: "BTS", language: "Korean", mood: "calm", youtubeId: "amnspvOH-EE" },
    { title: "River Flows in You", artist: "Yiruma", language: "Korean", mood: "calm", youtubeId: "7maJOI3QMu0" },
    { title: "Clair de Lune", artist: "Debussy (Piano)", language: "English", mood: "calm", youtubeId: "CvFH_6DNRCY" },
    { title: "Flightless Bird", artist: "Iron & Wine", language: "English", mood: "calm", youtubeId: "UfcAVejslrU" },
    { title: "Bloom", artist: "The Paper Kites", language: "English", mood: "calm", youtubeId: "hoNb6HuNmU0" },
    { title: "Ocean", artist: "Martin Garrix ft. Khalid", language: "English", mood: "calm", youtubeId: "OkyrIRyrRdY" },
    { title: "Skinny Love", artist: "Bon Iver", language: "English", mood: "calm", youtubeId: "ssdgFoHLwnk" },
    { title: "Holocene", artist: "Bon Iver", language: "English", mood: "calm", youtubeId: "TWcyIpul8OE" },
    { title: "Sparks", artist: "Coldplay", language: "English", mood: "calm", youtubeId: "OkyrIRyrRdY" },
    { title: "The Sound of Silence", artist: "Simon & Garfunkel", language: "English", mood: "calm", youtubeId: "4fWyzwo1xg0" },
    { title: "Tum Tak", artist: "A.R. Rahman", language: "Hindi", mood: "calm", youtubeId: "KQetemT1sWc" },
    { title: "Aye Zindagi", artist: "Shaan", language: "Hindi", mood: "calm", youtubeId: "seZMOTGCDag" },
    { title: "Safarnama", artist: "Lucky Ali", language: "Hindi", mood: "calm", youtubeId: "UfcAVejslrU" },
    { title: "O Re Piya", artist: "Rahat Fateh Ali Khan", language: "Hindi", mood: "calm", youtubeId: "hoNb6HuNmU0" },
    { title: "Lag Ja Gale", artist: "Lata Mangeshkar", language: "Hindi", mood: "calm", youtubeId: "KQetemT1sWc" },
    { title: "Jo Bhi Main", artist: "Mohit Chauhan", language: "Hindi", mood: "calm", youtubeId: "OkyrIRyrRdY" },
    { title: "Mann Kasturi", artist: "Benny Dayal", language: "Hindi", mood: "calm", youtubeId: "hoNb6HuNmU0" },
    { title: "Ikk Kudi", artist: "Diljit Dosanjh", language: "Punjabi", mood: "calm", youtubeId: "seZMOTGCDag" },
    { title: "Sucha Yaar", artist: "Satinder Sartaaj", language: "Punjabi", mood: "calm", youtubeId: "hoNb6HuNmU0" },
    { title: "Inaindha Kaigal", artist: "Vijay Prakash", language: "Tamil", mood: "calm", youtubeId: "UfcAVejslrU" },
    { title: "Adi Nee Mazhaiyaa", artist: "A.R. Rahman", language: "Tamil", mood: "calm", youtubeId: "OkyrIRyrRdY" },
    { title: "Nuvvante Naakishtam", artist: "Sid Sriram", language: "Telugu", mood: "calm", youtubeId: "OkyrIRyrRdY" },
    { title: "Bella Ciao", artist: "Various Artists", language: "Spanish", mood: "calm", youtubeId: "hoNb6HuNmU0" },
    { title: "Begin", artist: "BTS", language: "Korean", mood: "calm", youtubeId: "OkyrIRyrRdY" },
    { title: "Hana ni Naro", artist: "Little Glee Monster", language: "Japanese", mood: "calm", youtubeId: "KQetemT1sWc" },

    // ────────────── ANGRY ──────────────
    { title: "In the End", artist: "Linkin Park", language: "English", mood: "angry", youtubeId: "eVTXPUF4Oz4" },
    { title: "Numb", artist: "Linkin Park", language: "English", mood: "angry", youtubeId: "kXYiU_JCYtU" },
    { title: "Break Stuff", artist: "Limp Bizkit", language: "English", mood: "angry", youtubeId: "ZpUYjpKg9KY" },
    { title: "Killing in the Name", artist: "Rage Against the Machine", language: "English", mood: "angry", youtubeId: "bWXazVhlyxQ" },
    { title: "Apna Time Aayega", artist: "Ranveer Singh", language: "Hindi", mood: "angry", youtubeId: "kXYiU_JCYtU" },
    { title: "Sultan", artist: "KK & Vishal Dadlani", language: "Hindi", mood: "angry", youtubeId: "kXYiU_JCYtU" },
    { title: "Kill This Love", artist: "BLACKPINK", language: "Korean", mood: "angry", youtubeId: "2S24-y0Ij3Y" },
    { title: "Gangsta's Paradise", artist: "Coolio", language: "English", mood: "angry", youtubeId: "fPO76Jlnz6c" },
    { title: "Faint", artist: "Linkin Park", language: "English", mood: "angry", youtubeId: "LYU-8IFcDPw" },
    { title: "Given Up", artist: "Linkin Park", language: "English", mood: "angry", youtubeId: "0xyxtzD54rM" },
    { title: "Last Resort", artist: "Papa Roach", language: "English", mood: "angry", youtubeId: "ZpUYjpKg9KY" },
    { title: "Bodies", artist: "Drowning Pool", language: "English", mood: "angry", youtubeId: "04F4xlWSFh0" },
    { title: "Down with the Sickness", artist: "Disturbed", language: "English", mood: "angry", youtubeId: "ZpUYjpKg9KY" },
    { title: "Victimized", artist: "Linkin Park", language: "English", mood: "angry", youtubeId: "bWXazVhlyxQ" },
    { title: "Till I Collapse", artist: "Eminem", language: "English", mood: "angry", youtubeId: "kXYiU_JCYtU" },
    { title: "Dil Se Re", artist: "A.R. Rahman", language: "Hindi", mood: "angry", youtubeId: "jEooJiKC4DM" },
    { title: "Gabbar Is Back Title Track", artist: "Vishal Dadlani", language: "Hindi", mood: "angry", youtubeId: "bWXazVhlyxQ" },
    { title: "Bhaag D.K. Bose", artist: "Ram Sampath", language: "Hindi", mood: "angry", youtubeId: "jEooJiKC4DM" },
    { title: "Sadda Haq", artist: "Mohit Chauhan", language: "Hindi", mood: "angry", youtubeId: "bWXazVhlyxQ" },
    { title: "Porkalam", artist: "Vijay Sethupathi", language: "Tamil", mood: "angry", youtubeId: "jEooJiKC4DM" },
    { title: "Kaththi Title Track", artist: "Anirudh Ravichander", language: "Tamil", mood: "angry", youtubeId: "jEooJiKC4DM" },
    { title: "Break the Chain", artist: "Kailash Kher", language: "Hindi", mood: "angry", youtubeId: "jEooJiKC4DM" },
    { title: "Garrari", artist: "Diljit Dosanjh", language: "Punjabi", mood: "angry", youtubeId: "kXYiU_JCYtU" },
    { title: "Without Me", artist: "Eminem", language: "English", mood: "angry", youtubeId: "YVkUvmDQ3HY" },
    { title: "Blood Sweat & Tears", artist: "BTS", language: "Korean", mood: "angry", youtubeId: "hmE9f-TEutc" },
    { title: "Not Afraid", artist: "Eminem", language: "English", mood: "angry", youtubeId: "j5-yKhDd64s" },
    { title: "Rooftop", artist: "Yo Yo Honey Singh", language: "Hindi", mood: "angry", youtubeId: "kXYiU_JCYtU" },
    { title: "Judas", artist: "Lady Gaga", language: "English", mood: "angry", youtubeId: "jEooJiKC4DM" },

    // ────────────── PARTY ──────────────
    { title: "Uptown Funk", artist: "Bruno Mars", language: "English", mood: "party", youtubeId: "OPf0YbXqDm0" },
    { title: "Don't Start Now", artist: "Dua Lipa", language: "English", mood: "party", youtubeId: "oygrmJFKYZY" },
    { title: "Levitating", artist: "Dua Lipa", language: "English", mood: "party", youtubeId: "TUVcZfQe-Kw" },
    { title: "Blinding Lights", artist: "The Weeknd", language: "English", mood: "party", youtubeId: "4NRXx6U8ABQ" },
    { title: "Kala Chashma", artist: "Badshah & Neha Kakkar", language: "Hindi", mood: "party", youtubeId: "oygrmJFKYZY" },
    { title: "Kar Gayi Chull", artist: "Badshah & Neha Kakkar", language: "Hindi", mood: "party", youtubeId: "NTHz9ephYTw" },
    { title: "Nachde Ne Saare", artist: "Jasleen Royal", language: "Hindi", mood: "party", youtubeId: "OPf0YbXqDm0" },
    { title: "Rowdy Baby", artist: "Dhanush & Dhee", language: "Tamil", mood: "party", youtubeId: "OPf0YbXqDm0" },
    { title: "Arabesque", artist: "Anirudh", language: "Tamil", mood: "party", youtubeId: "OPf0YbXqDm0" },
    { title: "Buttabomma", artist: "Armaan Malik", language: "Telugu", mood: "party", youtubeId: "TUVcZfQe-Kw" },
    { title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", language: "Spanish", mood: "party", youtubeId: "kJQP7kiw5Fk" },
    { title: "Gangnam Style", artist: "PSY", language: "Korean", mood: "party", youtubeId: "9bZkp7q19f0" },
    { title: "How You Like That", artist: "BLACKPINK", language: "Korean", mood: "party", youtubeId: "ioNng23DkIM" },
    { title: "Lak 28 Kudi Da", artist: "Diljit Dosanjh", language: "Punjabi", mood: "party", youtubeId: "k4yXQPMsmKQ" },
    { title: "Shape of You", artist: "Ed Sheeran", language: "English", mood: "party", youtubeId: "JGwWNGJdvx8" },
    { title: "Cheap Thrills", artist: "Sia", language: "English", mood: "party", youtubeId: "nfWlot6h_JM" },
    { title: "One Dance", artist: "Drake", language: "English", mood: "party", youtubeId: "BoEKWtgJQAU" },
    { title: "Sorry", artist: "Justin Bieber", language: "English", mood: "party", youtubeId: "fRh_vgS2dFE" },
    { title: "God is a Woman", artist: "Ariana Grande", language: "English", mood: "party", youtubeId: "kHLHSlExFis" },
    { title: "Bad Guy", artist: "Billie Eilish", language: "English", mood: "party", youtubeId: "DyDfgMOUjCI" },
    { title: "Telephone", artist: "Lady Gaga ft. Beyoncé", language: "English", mood: "party", youtubeId: "4NRXx6U8ABQ" },
    { title: "Danka", artist: "Badshah", language: "Hindi", mood: "party", youtubeId: "OPf0YbXqDm0" },
    { title: "Abhi Toh Party Shuru Hui Hai", artist: "Bappi Lahiri & Usha Uthup", language: "Hindi", mood: "party", youtubeId: "OPf0YbXqDm0" },
    { title: "DJ Waley Babu", artist: "Badshah", language: "Hindi", mood: "party", youtubeId: "4NRXx6U8ABQ" },
    { title: "Garmi", artist: "Badshah & Neha Kakkar", language: "Hindi", mood: "party", youtubeId: "oygrmJFKYZY" },
    { title: "Illegal Weapon", artist: "Jasmine Sandlas & Garry Sandhu", language: "Punjabi", mood: "party", youtubeId: "oygrmJFKYZY" },
    { title: "GOAT", artist: "Diljit Dosanjh", language: "Punjabi", mood: "party", youtubeId: "k4yXQPMsmKQ" },
    { title: "Pagal", artist: "Badshah", language: "Hindi", mood: "party", youtubeId: "oygrmJFKYZY" },
    { title: "Bidi Bidi Bom Bom", artist: "Selena", language: "Spanish", mood: "party", youtubeId: "TUVcZfQe-Kw" },
    { title: "La Tortura", artist: "Shakira ft. Alejandro Sanz", language: "Spanish", mood: "party", youtubeId: "OPf0YbXqDm0" },
    { title: "Taki Taki", artist: "DJ Snake ft. Selena Gomez", language: "Spanish", mood: "party", youtubeId: "ixkoVwKQaJg" },
    { title: "Mic Drop", artist: "BTS", language: "Korean", mood: "party", youtubeId: "kTlv5_Bs8aw" },
    { title: "IDOL", artist: "BTS", language: "Korean", mood: "party", youtubeId: "pBuZEGYXA6E" },
    { title: "Pink Venom", artist: "BLACKPINK", language: "Korean", mood: "party", youtubeId: "TUVcZfQe-Kw" },
    { title: "Lovefool", artist: "The Cardigans", language: "English", mood: "party", youtubeId: "oygrmJFKYZY" },
    { title: "Pon de Replay", artist: "Rihanna", language: "English", mood: "party", youtubeId: "oygrmJFKYZY" },
    { title: "Ke$ha - Tik Tok", artist: "Kesha", language: "English", mood: "party", youtubeId: "iP6XpLQM2Cs" },
    { title: "Temperature", artist: "Sean Paul", language: "English", mood: "party", youtubeId: "oygrmJFKYZY" },

    // ────────────── NOSTALGIC ──────────────
    { title: "Bohemian Rhapsody", artist: "Queen", language: "English", mood: "nostalgic", youtubeId: "fJ9rUzIMcZQ" },
    { title: "Yesterday", artist: "The Beatles", language: "English", mood: "nostalgic", youtubeId: "NrgmdOz227I" },
    { title: "Hotel California", artist: "Eagles", language: "English", mood: "nostalgic", youtubeId: "BciS5krYL80" },
    { title: "Sweet Child O' Mine", artist: "Guns N' Roses", language: "English", mood: "nostalgic", youtubeId: "1w7OgIMMRc4" },
    { title: "Tujhe Dekha Toh", artist: "Kumar Sanu & Lata Mangeshkar", language: "Hindi", mood: "nostalgic", youtubeId: "n1WpP7iowLc" },
    { title: "Kal Ho Naa Ho", artist: "Sonu Nigam", language: "Hindi", mood: "nostalgic", youtubeId: "g0eO74UmRBs" },
    { title: "Lag Ja Gale", artist: "Lata Mangeshkar", language: "Hindi", mood: "nostalgic", youtubeId: "BciS5krYL80" },
    { title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh", language: "Hindi", mood: "nostalgic", youtubeId: "1w7OgIMMRc4" },
    { title: "Snehithane", artist: "Alaipayuthey", language: "Tamil", mood: "nostalgic", youtubeId: "1w7OgIMMRc4" },
    { title: "Memories", artist: "Maroon 5", language: "English", mood: "nostalgic", youtubeId: "SlPhMPnQ58k" },
    { title: "Don't Look Back in Anger", artist: "Oasis", language: "English", mood: "nostalgic", youtubeId: "r8OipmKFDeM" },
    { title: "Wonderwall", artist: "Oasis", language: "English", mood: "nostalgic", youtubeId: "bx1Bh8ZvH84" },
    { title: "November Rain", artist: "Guns N' Roses", language: "English", mood: "nostalgic", youtubeId: "8SbUC-UaAxE" },
    { title: "Wish You Were Here", artist: "Pink Floyd", language: "English", mood: "nostalgic", youtubeId: "IXdNnw99-Ic" },
    { title: "Stairway to Heaven", artist: "Led Zeppelin", language: "English", mood: "nostalgic", youtubeId: "xbhCPt6PZIU" },
    { title: "Let It Be", artist: "The Beatles", language: "English", mood: "nostalgic", youtubeId: "QDYfEBY9NM4" },
    { title: "Smells Like Teen Spirit", artist: "Nirvana", language: "English", mood: "nostalgic", youtubeId: "hTWKbfoikeg" },
    { title: "Shape of My Heart", artist: "Sting", language: "English", mood: "nostalgic", youtubeId: "n1WpP7iowLc" },
    { title: "Dil Hai Tumhara", artist: "Udit Narayan & Kavita Krishnamurthy", language: "Hindi", mood: "nostalgic", youtubeId: "n1WpP7iowLc" },
    { title: "Mere Dholna", artist: "Shreya Ghoshal & Udit Narayan", language: "Hindi", mood: "nostalgic", youtubeId: "fJ9rUzIMcZQ" },
    { title: "Koi Mil Gaya", artist: "Udit Narayan & Alka Yagnik", language: "Hindi", mood: "nostalgic", youtubeId: "1w7OgIMMRc4" },
    { title: "Tu Hi Re", artist: "Hariharan & Kavita Krishnamurthy", language: "Hindi", mood: "nostalgic", youtubeId: "BciS5krYL80" },
    { title: "Ek Ladki Thi Deewani Si", artist: "Kishore Kumar", language: "Hindi", mood: "nostalgic", youtubeId: "1w7OgIMMRc4" },
    { title: "Kehna Hi Kya", artist: "A.R. Rahman", language: "Hindi", mood: "nostalgic", youtubeId: "NrgmdOz227I" },
    { title: "Ek Pyar Ka Nagma Hai", artist: "Lata Mangeshkar", language: "Hindi", mood: "nostalgic", youtubeId: "n1WpP7iowLc" },
    { title: "Saathiya", artist: "Sonu Nigam", language: "Hindi", mood: "nostalgic", youtubeId: "BciS5krYL80" },
    { title: "Jab Hum Jawan Honge", artist: "Kishore Kumar & Asha Bhosle", language: "Hindi", mood: "nostalgic", youtubeId: "fJ9rUzIMcZQ" },
    { title: "Nenjinile", artist: "A.R. Rahman", language: "Tamil", mood: "nostalgic", youtubeId: "1w7OgIMMRc4" },
    { title: "Kadhal Rojave", artist: "A.R. Rahman", language: "Tamil", mood: "nostalgic", youtubeId: "1w7OgIMMRc4" },
    { title: "Mannipaaya", artist: "Benny Dayal", language: "Tamil", mood: "nostalgic", youtubeId: "1w7OgIMMRc4" },
    { title: "Nenene", artist: "M.M. Keeravani", language: "Telugu", mood: "nostalgic", youtubeId: "fJ9rUzIMcZQ" },
    { title: "El Condor Pasa", artist: "Simon & Garfunkel", language: "Spanish", mood: "nostalgic", youtubeId: "n1WpP7iowLc" },
    { title: "Rain and Tears", artist: "Aphrodite's Child", language: "English", mood: "nostalgic", youtubeId: "BciS5krYL80" },
    { title: "Mother", artist: "Pink Floyd", language: "English", mood: "nostalgic", youtubeId: "2Oo8QzDHimQ" },
    { title: "Goblin OST - Round and Round", artist: "Heize", language: "Korean", mood: "nostalgic", youtubeId: "n1WpP7iowLc" },
    { title: "Stay", artist: "BLACKPINK", language: "Korean", mood: "nostalgic", youtubeId: "NrgmdOz227I" },

    // ────────────── MOTIVATIONAL ──────────────
    { title: "Stronger (What Doesn't Kill You)", artist: "Kelly Clarkson", language: "English", mood: "motivational", youtubeId: "Xn676-fLq7I" },
    { title: "Fight Song", artist: "Rachel Platten", language: "English", mood: "motivational", youtubeId: "xo1VInw-SKc" },
    { title: "Hall of Fame", artist: "The Script ft. will.i.am", language: "English", mood: "motivational", youtubeId: "mk48xRzuNvA" },
    { title: "Believer", artist: "Imagine Dragons", language: "English", mood: "motivational", youtubeId: "7wtfhZwyrcc" },
    { title: "Unstoppable", artist: "Sia", language: "English", mood: "motivational", youtubeId: "cxjvTXo9WWM" },
    { title: "Chak De India", artist: "Sukhwinder Singh", language: "Hindi", mood: "motivational", youtubeId: "xo1VInw-SKc" },
    { title: "Zinda", artist: "Siddharth Mahadevan", language: "Hindi", mood: "motivational", youtubeId: "7wtfhZwyrcc" },
    { title: "Dangal", artist: "Daler Mehndi", language: "Hindi", mood: "motivational", youtubeId: "Xn676-fLq7I" },
    { title: "Verithanam", artist: "A.R. Rahman", language: "Tamil", mood: "motivational", youtubeId: "xo1VInw-SKc" },
    { title: "Not Today", artist: "BTS", language: "Korean", mood: "motivational", youtubeId: "9DwzBICPhdM" },
    { title: "Haan Kargi", artist: "Ammy Virk", language: "Punjabi", mood: "motivational", youtubeId: "mk48xRzuNvA" },
    { title: "Roar", artist: "Katy Perry", language: "English", mood: "motivational", youtubeId: "CevxZvSJLk8" },
    { title: "Remember the Name", artist: "Fort Minor", language: "English", mood: "motivational", youtubeId: "VDvr08sCPOc" },
    { title: "Man in the Mirror", artist: "Michael Jackson", language: "English", mood: "motivational", youtubeId: "PivWY9wn5ps" },
    { title: "Lose Yourself", artist: "Eminem", language: "English", mood: "motivational", youtubeId: "_Yhyp-_hX2s" },
    { title: "I Will Survive", artist: "Gloria Gaynor", language: "English", mood: "motivational", youtubeId: "mk48xRzuNvA" },
    { title: "Don't Stop Believin'", artist: "Journey", language: "English", mood: "motivational", youtubeId: "1k8craCGpgs" },
    { title: "Eye of the Tiger", artist: "Survivor", language: "English", mood: "motivational", youtubeId: "btPJPFnesV4" },
    { title: "We Will Rock You", artist: "Queen", language: "English", mood: "motivational", youtubeId: "-tJYN-eG1zk" },
    { title: "We Are the Champions", artist: "Queen", language: "English", mood: "motivational", youtubeId: "04854XqcfCY" },
    { title: "Rise Up", artist: "Andra Day", language: "English", mood: "motivational", youtubeId: "cxjvTXo9WWM" },
    { title: "Born This Way", artist: "Lady Gaga", language: "English", mood: "motivational", youtubeId: "wV1FrqwZyKw" },
    { title: "Heer", artist: "Javed Ali", language: "Hindi", mood: "motivational", youtubeId: "cxjvTXo9WWM" },
    { title: "Tujhse Naraaz Nahi Zindagi", artist: "Pankaj Udhas", language: "Hindi", mood: "motivational", youtubeId: "Xn676-fLq7I" },
    { title: "Sooraj Dooba Hai", artist: "Arijit Singh & Aditi Singh Sharma", language: "Hindi", mood: "motivational", youtubeId: "xo1VInw-SKc" },
    { title: "Lakshya Title Song", artist: "Shankar Mahadevan", language: "Hindi", mood: "motivational", youtubeId: "mk48xRzuNvA" },
    { title: "Bawara Mann", artist: "Shashwat Singh & Jonita Gandhi", language: "Hindi", mood: "motivational", youtubeId: "cxjvTXo9WWM" },
    { title: "Shukran Allah", artist: "Sonu Nigam & Shreya Ghoshal", language: "Hindi", mood: "motivational", youtubeId: "cxjvTXo9WWM" },
    { title: "Rang De Basanti", artist: "Daler Mehndi & A.R. Rahman", language: "Hindi", mood: "motivational", youtubeId: "xo1VInw-SKc" },
    { title: "Swades Title Song", artist: "A.R. Rahman", language: "Hindi", mood: "motivational", youtubeId: "xo1VInw-SKc" },
    { title: "Sare Jahan Se Accha", artist: "Lata Mangeshkar", language: "Hindi", mood: "motivational", youtubeId: "mk48xRzuNvA" },
    { title: "Carry On", artist: "Diljit Dosanjh", language: "Punjabi", mood: "motivational", youtubeId: "Xn676-fLq7I" },
    { title: "Dara", artist: "Satinder Sartaaj", language: "Punjabi", mood: "motivational", youtubeId: "cxjvTXo9WWM" },
    { title: "Surviva", artist: "Yuvan Shankar Raja", language: "Tamil", mood: "motivational", youtubeId: "xo1VInw-SKc" },
    { title: "Unakkenna Venum Sollu", artist: "Sathyaprakash", language: "Tamil", mood: "motivational", youtubeId: "Xn676-fLq7I" },
    { title: "Seeti Maar", artist: "Mangli", language: "Telugu", mood: "motivational", youtubeId: "7wtfhZwyrcc" },
    { title: "Vachinde", artist: "Sid Sriram", language: "Telugu", mood: "motivational", youtubeId: "7wtfhZwyrcc" },
    { title: "ON", artist: "BTS", language: "Korean", mood: "motivational", youtubeId: "Xn676-fLq7I" },
    { title: "Young Forever", artist: "BTS", language: "Korean", mood: "motivational", youtubeId: "cxjvTXo9WWM" },
    { title: "Nishimonogatari", artist: "Kenshi Yonezu", language: "Japanese", mood: "motivational", youtubeId: "Xn676-fLq7I" },
    { title: "A Whole New World", artist: "Peabo Bryson & Regina Belle", language: "English", mood: "motivational", youtubeId: "hZ1Rb9hC4JY" }
];

// Export for use in mood.js
window.SONG_DATABASE = SONG_DATABASE;
